spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
spring.data.mongodb:
  uri: mongodb://127.0.0.1:27017/numbers
  